from sqlalchemy import Column, Integer, Text, ForeignKey, create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
import datetime

Base = declarative_base()

class Product(Base):
    __tablename__ = 'Product'

    product_id = Column(Integer, primary_key=True, autoincrement=True)
    product_name = Column(Text, nullable=False)
    shipped_from = Column(Text, nullable=False)
    product_category = Column(Text, nullable=False)
    tiktok_product_link = Column(Text, nullable=False)
    product_price = Column(Text, nullable=False)
    lowest_price_30_days = Column(Text, nullable=False)
    product_earliest_date_recorded = Column(Text, nullable=False)
    from_shop_name = Column(Text, nullable=False)
    image_links = Column(Text, nullable=False)
    revenue_entity_id = Column(Integer, nullable=False)
    video_revenue_entity_id = Column(Integer, nullable=False)
    live_revenue_entity_id = Column(Integer, nullable=False)
    avg_unit_price_entity_id = Column(Integer, nullable=False)
    item_sold_entity_id = Column(Integer, nullable=False)
    mall_revenue_entity_id = Column(Integer, nullable=False)

class Creator(Base):
    __tablename__ = 'Creator'

    creator_id = Column(Integer, primary_key=True, autoincrement=True)
    creator_username = Column(Text, nullable=False)
    no_of_followers = Column(Text, nullable=False)
    debut_time = Column(Text, nullable=False)
    last_30_days_products = Column(Integer, nullable=False)
    creator_bio = Column(Text, nullable=False)
    tiktok_link = Column(Text)
    instagram_link = Column(Text)
    contact_email_address = Column(Text)
    creator_earliest_date_recorded = Column(Text, nullable=False)
    revenue_entity_id = Column(Integer, nullable=False)
    live_revenue_entity_id = Column(Integer, nullable=False)
    video_revenue_entity_id = Column(Integer, nullable=False)
    avg_unit_price_entity_id = Column(Integer, nullable=False)
    traffic_live_views_yesterday = Column(Text, nullable=False)
    traffic_live_views_per_day_last_7_days = Column(Text, nullable=False)
    traffic_live_views_per_day_last_30_days = Column(Text, nullable=False)
    traffic_live_views_per_day_last_90_days = Column(Text, nullable=False)
    traffic_live_views_per_day_last_180_days = Column(Text, nullable=False)
    traffic_live_views_last_7_days = Column(Text, nullable=False)
    traffic_live_views_last_30_days = Column(Text, nullable=False)
    traffic_live_views_last_90_days = Column(Text, nullable=False)
    traffic_live_views_last_180_days = Column(Text, nullable=False)
    video_views_yesterday = Column(Text, nullable=False)
    video_views_per_day_last_7_days = Column(Text, nullable=False)
    video_views_per_day_last_30_days = Column(Text, nullable=False)
    video_views_per_day_last_90_days = Column(Text, nullable=False)
    video_views_per_day_last_180_days = Column(Text, nullable=False)
    video_views_last_7_days = Column(Text, nullable=False)
    video_views_last_30_days = Column(Text, nullable=False)
    video_views_last_90_days = Column(Text, nullable=False)
    video_views_last_180_days = Column(Text, nullable=False)
    new_followers_yesterday = Column(Text, nullable=False)
    new_followers_per_day_last_7_days = Column(Text, nullable=False)
    new_followers_per_day_last_30_days = Column(Text, nullable=False)
    new_followers_per_day_last_90_days = Column(Text, nullable=False)
    new_followers_per_day_last_180_days = Column(Text, nullable=False)
    new_followers_last_7_days = Column(Text, nullable=False)
    new_followers_last_30_days = Column(Text, nullable=False)
    new_followers_last_90_days = Column(Text, nullable=False)
    new_followers_last_180_days = Column(Text, nullable=False)

class Video(Base):
    __tablename__ = 'Video'

    video_id = Column(Integer, primary_key=True, autoincrement=True)
    video_link = Column(Text, nullable=False)
    video_tags = Column(Text)
    video_music_info = Column(Text)
    revenue_entity_id = Column(Integer, nullable=False)
    video_revenue_entity_id = Column(Integer, nullable=False)
    item_sold_entity_id = Column(Integer, nullable=False)
    video_publish_date = Column(Text, nullable=False)
    video_duration = Column(Text, nullable=False)
    video_advertising_information = Column(Text)
    video_earliest_date_recorded = Column(Text, nullable=False)
    # from_creator = Column(Text, nullable=False)
    # on_product = Column(Text, nullable=False)
    video_views_yesterday = Column(Text, nullable=False)
    video_views_per_day_last_7_days = Column(Text, nullable=False)
    video_views_per_day_last_30_days = Column(Text, nullable=False)
    video_views_per_day_last_90_days = Column(Text, nullable=False)
    video_views_per_day_last_180_days = Column(Text, nullable=False)
    video_views_last_7_days = Column(Text, nullable=False)
    video_views_last_30_days = Column(Text, nullable=False)
    video_views_last_90_days = Column(Text, nullable=False)
    video_views_last_180_days = Column(Text, nullable=False)
    video_new_followers_yesterday = Column(Text, nullable=False)
    video_new_followers_per_day_last_7_days = Column(Text, nullable=False)
    video_new_followers_per_day_last_30_days = Column(Text, nullable=False)
    video_new_followers_per_day_last_90_days = Column(Text, nullable=False)
    video_new_followers_per_day_last_180_days = Column(Text, nullable=False)
    video_new_followers_last_7_days = Column(Text, nullable=False)
    video_new_followers_last_30_days = Column(Text, nullable=False)
    video_new_followers_last_90_days = Column(Text, nullable=False)
    video_new_followers_last_180_days = Column(Text, nullable=False)
    video_ad_view_ratio_yesterday = Column(Text, nullable=False)
    video_ad_view_ratio_last_7_days = Column(Text, nullable=False)
    video_ad_view_ratio_last_30_days = Column(Text, nullable=False)
    video_ad_view_ratio_last_90_days = Column(Text, nullable=False)
    video_ad_view_ratio_last_180_days = Column(Text, nullable=False)
    video_ad_revenue_ratio_yesterday = Column(Text, nullable=False)
    video_ad_revenue_ratio_last_7_days = Column(Text, nullable=False)
    video_ad_revenue_ratio_last_30_days = Column(Text, nullable=False)
    video_ad_revenue_ratio_last_90_days = Column(Text, nullable=False)
    video_ad_revenue_ratio_last_180_days = Column(Text, nullable=False)
    video_ad_spend_yesterday = Column(Text, nullable=False)
    video_ad_spend_last_7_days = Column(Text, nullable=False)
    video_ad_spend_last_30_days = Column(Text, nullable=False)
    video_ad_spend_last_90_days = Column(Text, nullable=False)
    video_ad_spend_last_180_days = Column(Text, nullable=False)
    video_ad_roas_yesterday = Column(Text, nullable=False)
    video_ad_roas_last_7_days = Column(Text, nullable=False)
    video_ad_roas_last_30_days = Column(Text, nullable=False)
    video_ad_roas_last_90_days = Column(Text, nullable=False)
    video_ad_roas_last_180_days = Column(Text, nullable=False)

class Live_Stream(Base):
    __tablename__ = 'Live_Stream'

    live_stream_id = Column(Integer, primary_key=True, autoincrement=True)
    live_stream_name = Column(Text)
    live_stream_product_count = Column(Text, nullable=False)
    live_revenue_entity_id = Column(Integer, nullable=False)
    avg_unit_price_entity_id = Column(Integer, nullable=False)
    item_sold_entity_id = Column(Integer, nullable=False)
    live_stream_top_3_category = Column(Text, nullable=False)
    live_stream_time = Column(Text, nullable=False)
    live_stream_duration = Column(Text, nullable=False)
    live_stream_creator = Column(Text, nullable=False)
    live_stream_online_viewers = Column(Text, nullable=False)
    live_stream_online_viewers_per_minute = Column(Text, nullable=False)
    live_stream_views = Column(Text, nullable=False)
    live_stream_views_per_minute = Column(Text, nullable=False)
    live_stream_item_sold = Column(Text, nullable=False)
    live_stream_item_sold_per_minute = Column(Text, nullable=False)

class Shop(Base):
    __tablename__ = 'Shop'

    shop_id = Column(Integer, primary_key=True, autoincrement=True)
    shop_name = Column(Text, nullable=False)
    shop_type = Column(Text, nullable=False)
    shop_earliest_date_recorded = Column(Text, nullable=False)
    revenue_entity_id = Column(Integer, nullable=False)
    avg_unit_price_entity_id = Column(Integer, nullable=False)
    item_sold_entity_id = Column(Integer, nullable=False)
    mall_revenue_entity_id = Column(Integer, nullable=False)
    shop_soa_revenue_yesterday = Column(Text, nullable=False)
    shop_soa_revenue_per_day_last_7_days = Column(Text, nullable=False)
    shop_soa_revenue_per_day_last_30_days = Column(Text, nullable=False)
    shop_soa_revenue_per_day_last_90_days = Column(Text, nullable=False)
    shop_soa_revenue_per_day_last_180_days = Column(Text, nullable=False)
    shop_soa_revenue_last_7_days = Column(Text, nullable=False)
    shop_soa_revenue_last_30_days = Column(Text, nullable=False)
    shop_soa_revenue_last_90_days = Column(Text, nullable=False)
    shop_soa_revenue_last_180_days = Column(Text, nullable=False)
    shop_affiliate_revenue_yesterday = Column(Text, nullable=False)
    shop_affiliate_revenue_per_day_last_7_days = Column(Text, nullable=False)
    shop_affiliate_revenue_per_day_last_30_days = Column(Text, nullable=False)
    shop_affiliate_revenue_per_day_last_90_days = Column(Text, nullable=False)
    shop_affiliate_revenue_per_day_last_180_days = Column(Text, nullable=False)
    shop_affiliate_revenue_last_7_days = Column(Text, nullable=False)
    shop_affiliate_revenue_last_30_days = Column(Text, nullable=False)
    shop_affiliate_revenue_last_90_days = Column(Text, nullable=False)
    shop_affiliate_revenue_last_180_days = Column(Text, nullable=False)
    shop_soa_revenue_share_yesterday = Column(Text, nullable=False)
    shop_soa_revenue_share_last_7_days = Column(Text, nullable=False)
    shop_soa_revenue_share_last_30_days = Column(Text, nullable=False)
    shop_soa_revenue_share_last_90_days = Column(Text, nullable=False)
    shop_soa_revenue_share_last_180_days = Column(Text, nullable=False)
    shop_aff_revenue_share_yesterday = Column(Text, nullable=False)
    shop_aff_revenue_share_last_7_days = Column(Text, nullable=False)
    shop_aff_revenue_share_last_30_days = Column(Text, nullable=False)
    shop_aff_revenue_share_last_90_days = Column(Text, nullable=False)
    shop_aff_revenue_share_last_180_days = Column(Text, nullable=False)
    shop_mall_revenue_share_yesterday = Column(Text, nullable=False)
    shop_mall_revenue_share_last_7_days = Column(Text, nullable=False)
    shop_mall_revenue_share_last_30_days = Column(Text, nullable=False)
    shop_mall_revenue_share_last_90_days = Column(Text, nullable=False)
    shop_mall_revenue_share_last_180_days = Column(Text, nullable=False)

class Category(Base):
    __tablename__ = 'Category'

    category_id = Column(Integer, primary_key=True, autoincrement=True)
    category_name = Column(Text, nullable=False)
    category_level = Column(Text, nullable=False)
    category_hierarchy = Column(Text, nullable=False)
    revenue_entity_id = Column(Integer, nullable=False)
    live_revenue_entity_id = Column(Integer, nullable=False)
    video_revenue_entity_id = Column(Integer, nullable=False)
    category_change_in_revenue_yesterday = Column(Text, nullable=False)
    category_change_in_revenue_7_days = Column(Text, nullable=False)
    category_change_in_revenue_30_days = Column(Text, nullable=False)
    category_change_in_revenue_90_days = Column(Text, nullable=False)
    category_change_in_revenue_180_days = Column(Text, nullable=False)
    category_no_of_shops_yesterday = Column(Text, nullable=False)
    category_no_of_shops_7_days = Column(Text, nullable=False)
    category_no_of_shops_30_days = Column(Text, nullable=False)
    category_no_of_shops_90_days = Column(Text, nullable=False)
    category_no_of_shops_180_days = Column(Text, nullable=False)
    category_revenue_growth_rate_yesterday = Column(Text, nullable=False)
    category_revenue_growth_rate_7_days = Column(Text, nullable=False)
    category_revenue_growth_rate_30_days = Column(Text, nullable=False)
    category_revenue_growth_rate_90_days = Column(Text, nullable=False)
    category_revenue_growth_rate_180_days = Column(Text, nullable=False)
    category_avg_revenue_per_shop_yesterday = Column(Text, nullable=False)
    category_avg_revenue_per_shop_7_days = Column(Text, nullable=False)
    category_avg_revenue_per_shop_30_days = Column(Text, nullable=False)
    category_avg_revenue_per_shop_90_days = Column(Text, nullable=False)
    category_avg_revenue_per_shop_180_days = Column(Text, nullable=False)
    category_top_3_shops_revenue_ratio_yesterday = Column(Text, nullable=False)
    category_top_3_shops_revenue_ratio_7_days = Column(Text, nullable=False)
    category_top_3_shops_revenue_ratio_30_days = Column(Text, nullable=False)
    category_top_3_shops_revenue_ratio_90_days = Column(Text, nullable=False)
    category_top_3_shops_revenue_ratio_180_days = Column(Text, nullable=False)
    category_top_10_shops_revenue_ratio_yesterday = Column(Text, nullable=False)
    category_soa_revenue_share_yesterday = Column(Text, nullable=False)
    category_soa_revenue_share_7_days = Column(Text, nullable=False)
    category_soa_revenue_share_30_days = Column(Text, nullable=False)
    category_soa_revenue_share_90_days = Column(Text, nullable=False)
    category_soa_revenue_share_180_days = Column(Text, nullable=False)
    category_aff_revenue_share_yesterday = Column(Text, nullable=False)
    category_aff_revenue_share_7_days = Column(Text, nullable=False)
    category_aff_revenue_share_30_days = Column(Text, nullable=False)
    category_aff_revenue_share_90_days = Column(Text, nullable=False)
    category_aff_revenue_share_180_days = Column(Text, nullable=False)
    category_mall_revenue_share_yesterday = Column(Text, nullable=False)
    category_mall_revenue_share_7_days = Column(Text, nullable=False)
    category_mall_revenue_share_30_days = Column(Text, nullable=False)
    category_mall_revenue_share_90_days = Column(Text, nullable=False)
    category_mall_revenue_share_180_days = Column(Text, nullable=False)